# Use the latest ubuntu image as base for the new image
# ubuntu is the image name and latest is a tag that 
# references a particular version of the image.
# In this case latest is always the latest LTS image
# at the time of writing this, it's 16.04.
FROM jupyter/datascience-notebook


ADD . $HOME

RUN conda install --yes --file requirements.txt